### ISSUE TITLE
How to replace <name> and <description>

### ISSUE THREAD

**Issue by damsorian** [michogar/CordovaConfigWebpackPlugin#7]
Is it possible to replace de `<name>` and `<description>` elements? like:
```javascript
new CordovaConfigWebpackPlugin({
    name: 'Custom Content',
    description: 'Custom Content',
})
```
Also, multiple replacements like: 
```javascript
new CordovaConfigWebpackPlugin({
  author: { 
    email: packageJson.author.email,
    href: packageJson.author.url,
  },
},
```

**Comment by michogar** [comment]
Hi, I have done some changes in the plugin. You can review them in this [PR](https://github.com/michogar/CordovaConfigWebpackPlugin/pull/8).

I will merge throughout the day.

**Comment by damsorian** [comment]
@michogar nice!, Look good to me
